# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = 'ubuntu/xenial64'
  config.disksize.size = '20GB'
  config.vm.hostname = "devops"

  config.vm.define :devops do |devops|
  end

  # Forward Concourse Port
  config.vm.network "forwarded_port", guest: 8080, host: 23234
  # Forward Nexus Port
  config.vm.network "forwarded_port", guest: 8081, host: 23235
  # Docker management
  config.vm.network "forwarded_port", guest: 9898, host: 23236

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.

  config.vm.provider "virtualbox" do |vb|
   vb.gui = false

   # Customize the amount of memory on the VM:
   vb.memory = "4092"
  end

  # Provisioning
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvvv"
    ansible.playbook = "playbook.yml"
    ansible.extra_vars = { ansible_ssh_user: 'ubuntu' }
    ansible.sudo = true
  end

end
